name: deploy
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *' # Everyday at 12am
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SSH conection remove directory and remake it
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -r /home/mdeleon/scripts
            mkdir /home/mdeleon/scripts

      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@5.2
        with:
          switches: -avz
          path: ./scripts
          remote_path: /home/mdeleon/
          remote_host: ${{ secrets.SSH_HOST_IP }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Generate Shell Script Unit Testing
        uses: vargiuscuola/gen-sh-unittest@v1.0
        id: action-gen-sh-unittest

      - name: gensh-unittest result
        run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"

      - name: SSH conection add privileges
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls-l
            chmod -R 755 /home/mdeleon/scripts
            ls -l
