name: Develop Auto-PR
on:
  push:
    branches: ['develop']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      name: checkout

    - name: Tests setup
      run: |
        touch prueba.txt
        touch ".htpasswd"
        chmod 777 prueba.txt
        chmod 777 ".htpasswd"
        #sudo htpasswd -b ".htpasswd" "user1" "user1"
    
    - name: Generate Shell Script Unit Testing First Script
      uses: sudo-bot/action-shunit2@latest
      with:
        cli: "./scriptTests.sh"

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "👑 *An automated PR*"
        pr_reviewer: "mdeleon"
        pr_draft: true
        github_token: ${{ secrets.TOKEN_REPOSITORY }}